### ISSUE TITLE
support target track from adjacent images

### ISSUE THREAD

**Issue by AlfredXiaSF** [lgrcia/prose#69]
In the target track task, the telescope direction moves with the target, and as a result, stars and objects in the images also move. This presents a challenge when attempting to track a target in adjacent images. 

To address the target track task, I implemented a `TargetTrack` block that aligns adjacent images to extract stars and uses a line model estimate to associate the track target.

The `TargetTrack` block is designed to extract stars from aligned adjacent images, which improves the accuracy of target tracking. It accomplishes this by aligning the images and then extracting the stars from the aligned image. Once the stars have been extracted, a line model estimate is used to associate the track target.

**Comment by lgrcia** [comment]
Thanks for this @AlfredXiaSF!

Can you show an example use case for this new block and sequence?

I came across a similar problem and I wonder how the solution I implemented differs from yours. I wrote the `MovingSource` block that moves the position of a single source (usually the moving one, while other are aligned to a reference set). Here is an example sequence using it:

```python
from prose import Sequence, blocks

s = Sequence([
    calib_block,
    blocks.Trim(),
    blocks.PointSourceDetection(n=100),
    blocks.AlignReferenceSources(ref),
    MovingSource(0, lambda im: (1000, 1000)),
    blocks.CentroidQuadratic(),
    blocks.vizualisation.VideoPlot(lambda im: im.show(), "test.mp4")
])

s.run(fm.all_images[0::20])
```
And here is the movie from the `blocks.vizualisation.VideoPlot` block (I saw a `movie` method in your implementation so this block might be useful to you).

https://user-images.githubusercontent.com/20612771/229600181-64d72ce3-fd99-4785-a6f9-139362957abb.mp4

As you can see the source `0` moves according to the positions given by the second argument of `MovingSource`: a function that takes an image as input and return the new source coordinates as output (so it can use the image WCS, time, or whatever is needed). Here I only forced source 0 to be at the center of the image. As you can see there is a meridian flip at then end of the video and the source is a bit off, but a good centroiding block may help.

So I am curious, how is this different from your implementation?

I am also asking because I thought using information from adjacent images could be done by storing this information in the block. But maybe it is a limited solution?

**Comment by AlfredXiaSF** [comment]
> Can you show an example use case for this new block and sequence (#68)?

Yes, here is the example:
```python
from prose import blocks, SlidingSequence
from ipd import IpdProperties, GetIpdProperties, write_ipd

seq_target_track = SlidingSequence([
    blocks.PointSourceDetection(threshold=detect_threshold),    # stars detection
    blocks.Cutouts(21),                                         # making stars cutouts
    blocks.MedianEPSF(),                                        # building PSF
    blocks.psf.Moffat2D(),                                      # modeling PSF
    blocks.target.TargetTrack(),                                # alignment
    IpdProperties(threshold=detect_threshold),                  # ipd properties
    GetIpdProperties(),                                         # get ipd properties
])

seq_target_track.run(fm_files, loader=MyFitsImage)

seq_target_track[-3].plot(ref.shape, plt.cm.tab10, which=slice(None, None, 5))
```
![image](https://user-images.githubusercontent.com/33239379/229812283-fd221b1c-b246-483a-bbab-702b0d6ea07c.png)


The `lines` attribute in the `TargetTrack` block saves target information. Every line is a list of source index in every image. If no target is detected in an image, a NaN value will be filled in the corresponding index. This allows for keeping track of the movement and position of the target over time, even if it is not detected in every frame.
`IpdProperties` and `GetIpdProperties` are two blocks used for get some source properties, such as source width, height, area...

The above image shows predicted line in all non star sources, z axis is time. The difference threshold to determin whether the source is a star is 2.5 pixel, which may be two small.

> I came across a similar problem and I wonder how the solution I implemented differs from yours. I wrote the `MovingSource` block that moves the position of a single source (usually the moving one, while other are aligned to a reference set). 

The idea of `MovingSource` block is awesome. 

> And here is the movie from the `blocks.vizualisation.VideoPlot` block (I saw a `movie` method in your implementation so this block might be useful to you).

Yes, it is very useful, I will follow that block.

> So I am curious, how is this different from your implementation?

To detect non-moving sources in adjacent images, I chose to align the images and compare the positions of the sources. However, there may be multiple moving sources in each image, which can complicate the process.

To address this, I implemented a Linear Model in the terminate function to fit the non-moving sources and associate them between images. This approach improves the accuracy of the source detection process and enables the system to correctly identify non-moving sources across multiple images.

However, when tracking a LEO target that moves very fast, aligning the reference image with all other images may not be feasible. This is because there may be no overlapping stars between the two images, which would prevent a match from being made. 
I think my implementation is quite complicated. I don't know if I made it clear.

> I am also asking because I thought using information from adjacent images could be done by storing this information in the block. But maybe it is a limited solution?

Yes, I tried this, save every image source in block, and track target in `terminate` function. It works, but a limited solution. I think there maight be other application need to get information from muliple images, so I impliment the `SlidingSequence`. But we can implement target track problem without this sequence absolutely, so it maybe not useful.

> (I feel I might be out of topic, just let me know :))

Thank you, your reply was very useful!

**Comment by lgrcia** [comment]
Excellent @AlfredXiaSF , thanks a lot for this insight! The need is absolutely legit and I think many people might benefit from it. I am interested in a more general implementation of that. For example, one that can account for blocks in the sequence requiring a different number of images to be loaded (and users not having to think about it). Here is what I propose:

Rather than implementing a new sequence, what about allowing blocks to have different lengths (see illustration below), and take as input a new object called `ImageGroup`. 
<p align="center" style="margin-bottom:-50px">
    <img src="https://user-images.githubusercontent.com/20612771/229911165-16136070-50d7-498a-beb3-a9960c53640b.png" width="500">
</p>

Here are the few benefit from it:
- A `Sequence` will automatically create the image group based on the maximum-length block. Then, depending on its size, it will feed a block either with a simple `Image` or an `ImageGroup` with the appropriate size. Bottom line is that users will not have to think about it, just create sequences with the blocks they need.
- The `Sequence` will be in charge of updating the group at each iteration.
- All users implementing a `Block` with `Block.length` > 1 will benefit from `ImageGroup` methods and attributes, such as:
  ```python
  # n: length, current: index of current
  images = ImageGroup(n=3, current=1)
   
  # methods
  len(images)
  images[0] # current
  images[-1] # previous
  images[+1] # next
  
  # attributes
  images.current # current
  images.previous # previous
  images.next # next
  ```
It is extremely close to what you did, only with a bit more generalization and abstracting all the image group logic outside of the block.

If you like the idea I can create a new branch from which you can pull and adapt to fit your needs.

**Comment by lgrcia** [comment]
Also a note that I created [contributions guidelines](https://github.com/lgrcia/prose/blob/3.0.0/docs/CONTRIBUTING.md). You are definitely working on core objects developments but you might also be interested in the [field-specific developments](https://github.com/lgrcia/prose/blob/3.0.0/docs/CONTRIBUTING.md) section.

**Comment by AlfredXiaSF** [comment]
@lgrcia That looks fantastic! The concept of `ImageGroup` is incredibly helpful in addressing my query. I am eagerly anticipating its implementation.

**Comment by lgrcia** [comment]
Great! I created the [buffer](https://github.com/lgrcia/prose/tree/buffer) branch on which you can find all of this. I renamed the objects (still not final) but basically blocks now have a `size` attribute and sequences rely on the `Buffer` object (another name for `ImageGroup`).

Please go ahead in adapting these objects to your needs. I am happy to help and discuss if needed!

**Comment by AlfredXiaSF** [comment]
OK, I read it and made a small change. I added an `__iter__` function to `buffer` so it can be used with `for` directly. This way, I can easily use it for other lists and behave like a sliding window.
Here is a example:
```python
buffer = Buffer(5)
datas = np.random.randint(0, 20, 20)
buffer.init(datas)
for i, current in enumerate(buffer):
    print(buffer.buffer)
    assert current == datas[i]
```
Can you check whether the changes are appropriate. Thank you!

**Comment by AlfredXiaSF** [comment]
Great! The changes are very good.  Thank you!

By the way, I still have some questions about the target track image process. 

- How do we determine the track target source when the telescope direction is not accurate? Currently, I believe that I can examine the sources in the first three images, align them with the first image, and select three sources from the three images. If the mean position of the source in the first and third images is equal to the position of the source in the second image, I consider it to be the track target.

- It is not possible to align the reference image to images that have no overlapping stars. This situation is quite common for LEO objects, as the direction of the telescope moves very fast. Perhaps we could update the sources of the reference image when aligning the reference image with each image. For example, when aligning the reference image with the second image, we could use a source that is present in the second image but not in the reference image to update the source of the reference image.

If it's not too much trouble, could you please review it and let me know if there are any further improvements I could make? I really appreciate your help.

**Comment by lgrcia** [comment]
- If you need an approximate position for the tracked source (assuming it remains the same in all images) , the way you described is probably the best. You could even push this further by detecting sources on something like 20 images (spread along the observation) and employ a density clustering algorithm (e.g. DBSCAN) to locate the tracked source and have an idea of its coordinates variance over the observation.

- I think in this case reference images are much less valuable (because not representative of all images). It also depends about your specific application. If you want the astrometry of the object, a simple option would be to detect stars in each image and use [`PlateSolve`](https://prose.readthedocs.io/en/3.0.0/md/generated/prose.blocks.catalogs.PlateSolve.html#prose.blocks.catalogs.PlateSolve).

**Comment by AlfredXiaSF** [comment]
Thank you for your reply!
The idea of use DBSCAN to locate the tracked source is great!

**Comment by lgrcia** [comment]
I am very happy about the outcome of this discussion. Thanks a lot for your work! I will close this issue then. Cheers!
